# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inar_objective <- function(gamma, y, mu) {
    .Call(`_poisrrr_inar_objective`, gamma, y, mu)
}

